### ISSUE TITLE
Parameters names

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/wt-nodejs-api#89]
Through the API develop, the route parameter names became less representative. To improve this we must rename those parameters in routes and swagger, 

### Update route parameters
- `hotels/:address` for `hotels/:hotelAddress`
- `units/:unit` for `units/:unitlAddress`
- `hotels/:type` for `unitTypes/:unitType`

### Update Swagger parameters
- `hotels/{address}` for `hotels/{hotelAddress}`
- `units/{unit}` for `units/{unitlAddress}`
- `hotels/{type}` for `unitTypes/{unitType}`

**Comment by JirkaChadima** [comment]
Closed by #97
